## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file b1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_23 = Integer(23); _sage_const_1 = Integer(1); _sage_const_26 = Integer(26); _sage_const_41 = Integer(41); _sage_const_2 = Integer(2); _sage_const_44 = Integer(44); _sage_const_57 = Integer(57); _sage_const_3 = Integer(3); _sage_const_60 = Integer(60); _sage_const_85 = Integer(85); _sage_const_4 = Integer(4); _sage_const_87 = Integer(87); _sage_const_90 = Integer(90); _sage_const_5 = Integer(5); _sage_const_93 = Integer(93); _sage_const_95 = Integer(95); _sage_const_6 = Integer(6); _sage_const_98 = Integer(98); _sage_const_100 = Integer(100); _sage_const_102 = Integer(102); _sage_const_104 = Integer(104); _sage_const_8 = Integer(8); _sage_const_107 = Integer(107); _sage_const_109 = Integer(109); _sage_const_9 = Integer(9); _sage_const_118 = Integer(118); _sage_const_120 = Integer(120); _sage_const_122 = Integer(122); _sage_const_124 = Integer(124); _sage_const_11 = Integer(11); _sage_const_128 = Integer(128); _sage_const_130 = Integer(130); _sage_const_12 = Integer(12); _sage_const_133 = Integer(133); _sage_const_135 = Integer(135); _sage_const_13 = Integer(13); _sage_const_138 = Integer(138); _sage_const_140 = Integer(140); _sage_const_14 = Integer(14); _sage_const_142 = Integer(142); _sage_const_146 = Integer(146); _sage_const_15 = Integer(15); _sage_const_148 = Integer(148); _sage_const_150 = Integer(150); _sage_const_16 = Integer(16); _sage_const_154 = Integer(154); _sage_const_156 = Integer(156); _sage_const_17 = Integer(17); _sage_const_159 = Integer(159); _sage_const_161 = Integer(161); _sage_const_18 = Integer(18); _sage_const_164 = Integer(164); _sage_const_166 = Integer(166); _sage_const_19 = Integer(19); _sage_const_168 = Integer(168); _sage_const_170 = Integer(170); _sage_const_20 = Integer(20); _sage_const_173 = Integer(173)## This file (b1.sagetex.sage) was *autogenerated* from b1.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('b1', version='2020/08/12 v3.5', version_check=True)
try:
 _st_.current_tex_line = _sage_const_7 
 _st_.commandline(_sage_const_0 , r"""
    sage: N = matrix(RDF,[[0, 0, 0, 0, 0.5 , 0.5, 0],[1/3, 0, 1/3, 0, 0, 1/3, 0],[0, 0, 0, 0.5, 0 , 0.5, 0],[0, 0, 0, 0, 0, 1, 0],[0.25, 0, 0, 0.25, 0, 0.25, 0.25],[0.5, 0.5, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0 , 0, 0]])
    sage: latex("N(x)= " + latex(N))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_10 )
try:
 _st_.current_tex_line = _sage_const_23 
 _st_.commandline(_sage_const_1 , r"""
    sage: Q = matrix(RDF ,[[0, 0, 0, 0, 0.5 , 0.5, 0],[1/3, 0, 1/3, 0, 0, 1/3, 0],[0, 0, 0, 0.5, 0 , 0.5, 0],[0, 0, 0, 0, 0, 1, 0],[0.25, 0, 0, 0.25, 0, 0.25, 0.25],[0.5, 0.5, 0, 0, 0, 0, 0],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7]])
    sage: latex("Q(x)= " + latex(Q))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_26 )
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.commandline(_sage_const_2 , r"""
    sage: A = matrix(RDF ,[[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7],[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7]])
    sage: latex("A(x)= " + latex(A))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.commandline(_sage_const_3 , r"""
    sage: P=0.85*Q+0.15*A
    sage: latex("P(x)= " + latex(P))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_60 )
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.commandline(_sage_const_4 , r"""
    sage: latex("Valores propios:" + latex(P.eigenvalues()))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.commandline(_sage_const_5 , r"""
    sage: p=P.characteristic_polynomial()
    sage: latex("p(x)= " + latex(p))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_93 )
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.commandline(_sage_const_6 , r"""
    sage: D = diagonal_matrix([P.eigenvalues()[0], P.eigenvalues()[1],P.eigenvalues()[2],P.eigenvalues()[3],P.eigenvalues()[4],P.eigenvalues()[5],P.eigenvalues()[6]])
    sage: latex("D=" + latex(D))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.commandline(_sage_const_7 , r"""
    sage: latex("TODO=" + latex(P.eigenvectors_right()))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.commandline(_sage_const_8 , r"""
    sage: latex("TODO=" + latex(P.eigenmatrix_right()[0]))
    sage: latex("TODO=" + latex(P.eigenmatrix_right()[1]))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_107 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.commandline(_sage_const_9 , r"""
    sage: q1=(P.eigenvectors_right()[0])[1][0];
    sage: q2=(P.eigenvectors_right()[1])[1][0];
    sage: q3=(P.eigenvectors_right()[2])[1][0];
    sage: q4=(P.eigenvectors_right()[3])[1][0];
    sage: q5=(P.eigenvectors_right()[4])[1][0];
    sage: q6=(P.eigenvectors_right()[5])[1][0];
    sage: q7=(P.eigenvectors_right()[6])[1][0];
    sage: latex("q1="+ latex(q1) + " q2=" + latex(q2) + " q3="+ latex(q3) + " q4="+ latex(q4))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_118 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.commandline(_sage_const_10 , r"""
    sage: latex("q1= " + latex(q1))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_122 )
try:
 _st_.current_tex_line = _sage_const_124 
 _st_.commandline(_sage_const_11 , r"""
    sage: Q=column_matrix([q1,q2,q3,q4,q5,q6,q7]);
    sage: latex("Q= " + latex(Q))
    sage: latex(norm(P-Q*D*Q.inverse())<=10^(-10))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_128 )
try:
 _st_.current_tex_line = _sage_const_130 
 _st_.commandline(_sage_const_12 , r"""
    sage: mo=matrix(RDF,[1, 0, 0, 0, 0, 0, 0])
    sage: latex(mo*Q*D^100*Q.inverse())
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_133 )
try:
 _st_.current_tex_line = _sage_const_135 
 _st_.commandline(_sage_const_13 , r"""
    sage: z=(0.221980001405918,0.15271641500884678, 0.07125255257058884,0.08425917197181364, 0.12232440224893072,0.29349061966454393, 0.05397683712931336)
    sage: latex("z= " + latex(z))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_138 )
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.commandline(_sage_const_14 , r"""
    sage: sum(z)
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_142 )
try:
 _st_.current_tex_line = _sage_const_146 
 _st_.commandline(_sage_const_15 , r"""
    sage: G=P.transpose()
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.commandline(_sage_const_16 , r"""
    sage: latex("G="+ latex(G) + " Valores propios:" + latex(G.eigenvalues()))
    sage: p=G.characteristic_polynomial()
    sage: latex("p(x)=  "+ latex(p))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_154 )
try:
 _st_.current_tex_line = _sage_const_156 
 _st_.commandline(_sage_const_17 , r"""
    sage: latex("TODO=" + latex(G.eigenmatrix_right()[0]))
    sage: latex("TODO=" + latex(G.eigenmatrix_right()[1]))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_159 )
try:
 _st_.current_tex_line = _sage_const_161 
 _st_.commandline(_sage_const_18 , r"""
    sage: e1=(G.eigenvectors_right()[0])[1][0];
    sage: latex("e1=  "+ latex(e1))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_164 )
try:
 _st_.current_tex_line = _sage_const_166 
 _st_.commandline(_sage_const_19 , r"""
    sage: sum(e1)
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_170 
 _st_.commandline(_sage_const_20 , r"""
    sage: SOL=1/(sum(e1))*e1
    sage: latex("Solución=  "+ latex(SOL))
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_173 )
_st_.endofdoc()

